[package]
name = "hera"
version = "0.1.0"
description = "Hera is a Rust implementation of the OP Stack Rollup Node"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Workspace
eyre.workspace = true
alloy.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
url.workspace = true

# Workspace Crates
op-net.workspace = true
