reorder_imports = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
imports_granularity = "Crate"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
