[package]
name = "rollup"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
kona-providers = { path = "../kona-providers" }

# Workspace
eyre.workspace = true
tracing.workspace = true
clap.workspace = true
async-trait.workspace = true
tokio.workspace = true
alloy.workspace = true

# Reth Dependencies
reth.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true

# OP Stack Dependencies
kona-derive.workspace = true
kona-primitives.workspace = true
superchain-registry = { workspace = true, default-features = false }

# Misc
url = "2.5.2"
serde_json = "1"
reqwest = "0.12.7"

[features]
default = ["online"]
online = ["kona-derive/online"]
