[package]
name = "op-rs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# Local Dependencies
rollup = { path = "../../crates/rollup" }

# Workspace
eyre.workspace = true
tracing.workspace = true
clap.workspace = true

# Reth Dependencies
reth.workspace = true
reth-node-ethereum.workspace = true

# OP Stack Dependencies
superchain-registry = { workspace = true, default-features = false }
